### ISSUE TITLE
Clone repo & push commits

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/osmify#1]
@biplovbhandari 

Here's how I clone the repo and push my commits.

```bash
$ git clone git@github.com:osmottawa/osmify.git
$ cd osmify
$ git push
```

If you've never pushed to github before, you might need to register your ssh public key with GitHub.

```
$ ssh-keygen
... press enter for all the default settings
```
Then in your home directory `.ssh`, you need to copy paste `id_rsa.pub` to your Github registered keys.

Mine looks like this:

`~/.ssh/id_rsa.pub`
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTKIsW/i+V8FHCMzRJUKvMZDKJV7GhKrAIPfm04Lcf+NFUzvKRSNHMaRrHclf+NWTZxHLb27X6yE58PzID9OkcrGDV+1mtT85NyXP+ixOmw4Nqrvm5FqWD7CfMIFxY0Z0OFiVGJlxrhxfCroF2KRcOolief71LWgVdpbWnOmrP68TXrIVhh/3nEc7k4kx9+Bo5RB5oPvB99o+qvLQKYyfbzdZhPl9rpTfIDFbc7Q2yNvDM8e53mqkRbHJrpBnqmb1br+Mr9/K8GXjU3Zh9qKMPNzFc+q4F0l0/+YF03x0Lrtis9XtNkelB/RpgNgQpXU3s4tLzu7nLh//n3HErU/x denis@ubuntu
```

In your GitHub settings, you'll find **SSH and GPG keys**.

![image](https://cloud.githubusercontent.com/assets/550895/22192866/97a8a834-e105-11e6-9bfd-0fb32e1778ae.png)

Create a new key with what you've copied from `id_rsa.pub`

Once that key is in GitHub, you'll be able to send commits without having to put your username & password and you shouldn't be getting those 403 messages.

**Comment by biplovbhandari** [comment]
@DenisCarriere 

I already have SSH. However, I created again (Windows HP) and tried to push. Still, I get an authentication error.
 
![image](https://cloud.githubusercontent.com/assets/4207677/22193493/44f7fc98-e16e-11e6-9448-41c6fffd26e1.png)

![image](https://cloud.githubusercontent.com/assets/4207677/22193507/5e1f7764-e16e-11e6-97eb-bd2993ebbf57.png)

Maybe you have to add my account as instructed here: https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user/

**Comment by DenisCarriere** [comment]
@biplovbhandari Oops, you're correct, I thought I added you as an `Owner` and not a `member` of the OSMOttawa organization, you should have access now.

**Comment by biplovbhandari** [comment]
@DenisCarriere resolved..thanks

**Comment by DenisCarriere** [comment]
@biplovbhandari Good to hear! 👍 

I'll catch up tomorrow.
